// constants/farm_constants.dart

const List<String> farmList = [
  'Farm 1 - Ranchi',
  'Farm 2 - Jamshedpur',
  'Farm 3 - Dhanbad',
  'Farm 4 - Bokaro',
  'Farm 5 - Hazaribagh',
  'Farm 6 - Giridih',
  'Farm 7 - Deoghar',
  'Farm 8 - Palamu',
  'Farm 9 - Gumla',
  'Farm 10 - Khunti',
  'Farm 11 - Chaibasa',
  'Farm 12 - Simdega',
  'Farm 13 - Ramgarh',
  'Farm 14 - Lohardaga',
  'Farm 15 - Jamtara',
  'Farm 16 - Pakur',
  'Farm 17 - Latehar',
  'Farm 18 - Dumka',
  'Farm 19 - Godda',
  'Farm 20 - Sahebganj',
  'Farm 21 - Koderma',
  'Farm 22 - Chatra',
  'Farm 23 - Saraikela',
  'Farm 24 - Garhwa',
  'Farm 25 - Chirkunda',
  'Farm 26 - Chas',
  'Farm 27 - Mango',
  'Farm 28 - Baghmara',
  'Farm 29 - Jharia',
  'Farm 30 - Katras',
  'Farm 31 - Madhupur',
  'Farm 32 - Mihijam',
  'Farm 33 - Rajmahal',
  'Farm 34 - Tundi',
  'Farm 35 - Tisri',
  'Farm 36 - Sijhua',
  'Farm 37 - Daltonganj',
  'Farm 38 - Chandil',
  'Farm 39 - Dumri',
  'Farm 40 - Bermo',
  'Farm 41 - Phusro',
  'Farm 42 - Tenughat',
  'Farm 43 - Chandrapura',
  'Farm 44 - Rajrappa',
  'Farm 45 - Basia',
  'Farm 46 - Bishnugarh',
  'Farm 47 - Barkagaon',
  'Farm 48 - Jhumri Telaiya',
  'Farm 49 - Barhi',
  'Farm 50 - Chakradharpur',
];
